name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.0.6
      options: '--entrypoint /usr/bin/env'

    steps:
      - uses: actions/checkout@v2

      - name: Run test
        run: cd ./test && /bin/bash ./run-test.sh
