name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - uses: actions/checkout@v2

      - name: Working directory
        run: pwd

      - name: Show files in test directory
        run: |
          pwd
          ls -l ./test
        working-directory: test

      - name: Run test
        run: ./test/run-test.sh
        working-directory: test
